plugins {
    id 'java'
    id 'application'
    id("net.ltgt.errorprone") version "4.1.0"
}

group = 'com.example.loveletter'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    errorprone("com.google.errorprone:error_prone_core:2.20.0")
}

import java.util.Properties

def config = new Properties()
file('../config.properties').withInputStream { stream ->
    config.load(stream)
}

def serverPort = config.getProperty('server.port') ?: 12345
def serverHost = config.getProperty('server.host') ?: 'localhost'

application {
    applicationDefaultJvmArgs = ["-Dserver.port=${serverPort}"]
    mainClass = 'com.example.loveletter.TCPClient'
}

tasks.withType(JavaCompile).configureEach {
    options.errorprone.disableWarningsInGeneratedCode.set(true)
}

run {
    standardInput = System.in
}